// Pico W portable wifi server
// brings up an access point and serves a small html page on port 80
// you can turn the onboard LED on/off, see the temperature,
// download a test pdf, or shut the server down

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "hardware/adc.h"
#include "lwip/tcp.h"
#include "lwip/pbuf.h"
#include "dhcpserver.h"  // tiny DHCP server from pico-examples - hands out IPs to clients
#include "pdf_data.h"    // generated by: xxd -i test.pdf > pdf_data.h

#define SSID     "PicoW_Server"
#define PASSWORD "12345678"
#define PORT     80

// keep track of what the led is doing and whether the main loop should keep running
bool led_on = false;
bool running = true;


// read the temperature from the chip's internal sensor (channel 4 on the adc)
float read_temp() {
    adc_select_input(4);
    uint16_t raw = adc_read();
    float volts = raw * (3.3f / 4096.0f);
    // formula from the rp2040 datasheet
    return 27.0f - (volts - 0.706f) / 0.001721f;
}


// fill in the html page with the current led state and temperature
void build_page(char *out, int max_len) {
    float t = read_temp();
    const char *state_str;
    if (led_on) {
        state_str = "ON";
    } else {
        state_str = "OFF";
    }

    snprintf(out, max_len,
        "<!DOCTYPE html>"
        "<html>"
        "<head><title>Pico W</title></head>"
        "<body>"
        "<h1>Pico W Server</h1>"
        "<form action=\"/lighton\"><input type=\"submit\" value=\"LED On\"></form>"
        "<form action=\"/lightoff\"><input type=\"submit\" value=\"LED Off\"></form>"
        "<form action=\"/pdf/test.pdf\"><input type=\"submit\" value=\"Test PDF\"></form>"
        "<form action=\"/close\"><input type=\"submit\" value=\"Shutdown\"></form>"
        "<p>LED: %s | Temp: %.2fC</p>"
        "</body>"
        "</html>",
        state_str, t);
}


// write a normal html response back to the client
void send_html(struct tcp_pcb *pcb, const char *body) {
    char header[200];
    int body_len = strlen(body);
    snprintf(header, sizeof(header),
        "HTTP/1.0 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "Content-Length: %d\r\n"
        "\r\n",
        body_len);
    tcp_write(pcb, header, strlen(header), TCP_WRITE_FLAG_COPY);
    tcp_write(pcb, body, body_len, TCP_WRITE_FLAG_COPY);
    tcp_output(pcb);
}


// write the embedded pdf back to the client
void send_pdf(struct tcp_pcb *pcb) {
    char header[200];
    snprintf(header, sizeof(header),
        "HTTP/1.0 200 OK\r\n"
        "Content-Type: application/pdf\r\n"
        "Content-Length: %u\r\n"
        "\r\n",
        test_pdf_len);
    tcp_write(pcb, header, strlen(header), TCP_WRITE_FLAG_COPY);
    tcp_write(pcb, test_pdf, test_pdf_len, TCP_WRITE_FLAG_COPY);
    tcp_output(pcb);
}


// gets called whenever a client sends us bytes
err_t recv_cb(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err) {
    char *buf = (char *)arg;

    // p == NULL means the client closed the connection
    if (p == NULL) {
        free(buf);
        return tcp_close(pcb);
    }

    // copy the request into our buffer and null-terminate it
    int n = p->tot_len;
    if (n > 1023) {
        n = 1023;
    }
    pbuf_copy_partial(p, buf, n, 0);
    buf[n] = '\0';
    pbuf_free(p);

    // pull the path out of the request line
    // the request line looks like:  GET /lighton HTTP/1.1
    // so the path is between the first and second space
    char path[100];
    path[0] = '\0';
    char *first_space = strchr(buf, ' ');
    if (first_space != NULL) {
        first_space++;
        char *second_space = strchr(first_space, ' ');
        if (second_space != NULL) {
            int len = second_space - first_space;
            if (len > 99) len = 99;
            strncpy(path, first_space, len);
            path[len] = '\0';
        }
    }
    // if there's a ?query at the end, cut it off
    char *q = strchr(path, '?');
    if (q != NULL) {
        *q = '\0';
    }

    printf("request: %s\n", path);

    // decide what to do based on the path the client asked for
    if (strcmp(path, "/favicon.ico") == 0) {
        // browsers always ask for this, we don't have one, send a 404
        const char *resp = "HTTP/1.0 404 Not Found\r\n\r\n";
        tcp_write(pcb, resp, strlen(resp), TCP_WRITE_FLAG_COPY);
        tcp_output(pcb);
    }
    else if (strcmp(path, "/lighton") == 0) {
        led_on = true;
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);
        char page[1024];
        build_page(page, sizeof(page));
        send_html(pcb, page);
    }
    else if (strcmp(path, "/lightoff") == 0) {
        led_on = false;
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 0);
        char page[1024];
        build_page(page, sizeof(page));
        send_html(pcb, page);
    }
    else if (strcmp(path, "/close") == 0) {
        send_html(pcb, "<html><body><h1>Shutting down...</h1></body></html>");
        running = false;
    }
    else if (strcmp(path, "/pdf/test.pdf") == 0) {
        send_pdf(pcb);
    }
    else {
        // anything else just shows the main page
        char page[1024];
        build_page(page, sizeof(page));
        send_html(pcb, page);
    }

    return ERR_OK;
}


// gets called if lwip hits an error on the connection
void err_cb(void *arg, err_t err) {
    char *buf = (char *)arg;
    if (buf != NULL) {
        free(buf);
    }
    printf("tcp error: %d\n", err);
}


// gets called when a new client connects to our server
err_t accept_cb(void *arg, struct tcp_pcb *pcb, err_t err) {
    if (err != ERR_OK || pcb == NULL) {
        return ERR_VAL;
    }
    // give this connection its own little request buffer
    char *buf = calloc(1024, sizeof(char));
    if (buf == NULL) {
        return ERR_MEM;
    }
    tcp_arg(pcb, buf);
    tcp_recv(pcb, recv_cb);
    tcp_err(pcb, err_cb);
    return ERR_OK;
}


int main() {
    stdio_init_all();

    // get the wifi chip going
    if (cyw43_arch_init() != 0) {
        printf("wifi init failed\n");
        return 1;
    }

    // turn on the adc so we can read the temperature sensor later
    adc_init();
    adc_set_temp_sensor_enabled(true);

    // start broadcasting our own wifi network
    cyw43_arch_enable_ap_mode(SSID, PASSWORD, CYW43_AUTH_WPA2_AES_PSK);
    printf("AP started: %s\n", SSID);

    // start a dhcp server so clients can actually get an IP when they connect
    // without this, phones say "couldn't get IP address" and never finish joining
    ip_addr_t gw;
    ip_addr_t mask;
    gw.addr = PP_HTONL(CYW43_DEFAULT_IP_AP_ADDRESS);   // the Pico is 192.168.4.1
    mask.addr = PP_HTONL(CYW43_DEFAULT_IP_MASK);       // 255.255.255.0
    dhcp_server_t dhcp_server;
    dhcp_server_init(&dhcp_server, &gw, &mask);
    printf("DHCP server started\n");

    // set up the tcp listener on port 80
    struct tcp_pcb *pcb = tcp_new();
    if (pcb == NULL) {
        printf("tcp_new failed\n");
        return 1;
    }
    if (tcp_bind(pcb, IP_ADDR_ANY, PORT) != ERR_OK) {
        printf("tcp_bind failed\n");
        return 1;
    }
    pcb = tcp_listen(pcb);
    tcp_accept(pcb, accept_cb);
    printf("listening on port %d\n", PORT);

    // main loop - just keep the network stack ticking
    while (running) {
        cyw43_arch_poll();
        sleep_ms(1);
    }

    dhcp_server_deinit(&dhcp_server);
    cyw43_arch_deinit();
    printf("server stopped\n");
    return 0;
}
